# Generated by Django 5.2 on 2025-05-02 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('query_id', models.IntegerField(db_index=True)),
                ('results_count', models.IntegerField(db_index=True)),
                ('milliseconds', models.FloatField()),
                ('query_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-query_time'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ipAddress', models.CharField(db_index=True, max_length=100)),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
                ('value11', models.IntegerField()),
                ('value12', models.IntegerField()),
                ('value13', models.IntegerField()),
                ('value14', models.IntegerField()),
                ('value15', models.IntegerField()),
                ('value16', models.IntegerField()),
                ('value17', models.IntegerField()),
                ('value18', models.IntegerField()),
                ('value19', models.IntegerField()),
                ('value20', models.IntegerField()),
                ('value21', models.IntegerField()),
                ('depressionScore', models.IntegerField(default=0)),
                ('anxietyScore', models.IntegerField(default=0)),
                ('stressScore', models.IntegerField(default=0)),
                ('globalScore', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('token', models.CharField(db_index=True, max_length=6, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_registration_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
