# Generated by Django 5.2 on 2025-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('value6', models.IntegerField()),
                ('value7', models.IntegerField()),
                ('value8', models.IntegerField()),
                ('value9', models.IntegerField()),
                ('value10', models.IntegerField()),
                ('value11', models.IntegerField()),
                ('value12', models.IntegerField()),
                ('value13', models.IntegerField()),
                ('value14', models.IntegerField()),
                ('value15', models.IntegerField()),
                ('value16', models.IntegerField()),
                ('value17', models.IntegerField()),
                ('value18', models.IntegerField()),
                ('value19', models.IntegerField()),
                ('value20', models.IntegerField()),
                ('value21', models.IntegerField()),
                ('depressionScore', models.IntegerField(default=0)),
                ('anxietyScore', models.IntegerField(default=0)),
                ('stressScore', models.IntegerField(default=0)),
                ('globalScore', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
