# Generated by Django 5.2 on 2025-05-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registrationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('query_id', models.IntegerField(db_index=True)),
                ('results_count', models.IntegerField(db_index=True)),
                ('milliseconds', models.FloatField()),
                ('query_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-query_time'],
            },
        ),
    ]
